---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sealedsecret.yaml
  - bootstrap-configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - certificate.yaml
  - bootstrap-job.yaml
