---
apiVersion: v1
kind: Service
metadata:
  name: headscale-admin
  namespace: headscale-admin
spec:
  selector:
    app: headscale-admin
  ports:
    - name: http
      port: 80
      targetPort: http
