---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`weave.jackhumes.com`)
      kind: Rule
      services:
        - name: weave-gitops
          port: 9001
  tls:
    certResolver: letsencrypt
