---
apiVersion: v1
kind: Service
metadata:
  name: profilarr
  namespace: profilarr
  labels:
    app: profilarr
spec:
  selector:
    app: profilarr
  ports:
    - name: http
      port: 6868
      targetPort: 6868
      protocol: TCP
  type: ClusterIP
