---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: changedetection-cert
  namespace: changedetection
spec:
  secretName: changedetection-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - changes.lab.jackhumes.com
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: changedetection
  namespace: changedetection
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`changes.lab.jackhumes.com`)
      kind: Rule
      middlewares:
        - name: tinyauth-forwardauth
      services:
        - name: changedetection
          port: 5000
  tls:
    secretName: changedetection-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: changedetection-http
  namespace: changedetection
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`changes.lab.jackhumes.com`)
      kind: Rule
      services:
        - name: changedetection
          port: 5000
      middlewares:
        - name: redirect-https
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: changedetection
spec:
  redirectScheme:
    scheme: https
    permanent: true
