---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headplane
  namespace: headplane
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`headscale.jackhumes.com`) && PathPrefix(`/admin`)
      kind: Rule
      services:
        - name: headplane
          port: 3000
  tls:
    secretName: headscale-tls
