---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headscale
  namespace: headscale
spec:
  entryPoints:
    - websecure
  routes:
    # Route everything to Headscale (except /admin which is handled by headplane IngressRoute)
    - match: (Host(`headscale.jackhumes.com`) || Host(`headscale-funnel.taila62ed.ts.net`)) && !PathPrefix(`/admin`)
      kind: Rule
      services:
        - name: headscale
          port: 8080
  tls:
    secretName: headscale-tls
