---
apiVersion: v1
kind: Service
metadata:
  name: crowdsec-lapi
  namespace: crowdsec
spec:
  selector:
    app: crowdsec
  ports:
    - name: lapi
      port: 8080
      targetPort: lapi
      protocol: TCP
  type: ClusterIP
