---
apiVersion: v1
kind: Service
metadata:
  name: shelfmark
  namespace: shelfmark
  labels:
    app: shelfmark
spec:
  selector:
    app: shelfmark
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      protocol: TCP
  type: ClusterIP
