---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - pvc.yaml
  - configmap.yaml
  - nginx-configmap.yaml
  - sealedsecret.yaml
  - deployment.yaml
