---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sealedsecret.yaml  # Use SealedSecret instead of plain Secret
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - middleware.yaml
  - ingressroute.yaml
