---
apiVersion: v1
kind: Service
metadata:
  name: lldap
  namespace: lldap
  labels:
    app: lldap
spec:
  type: ClusterIP
  ports:
  - port: 3890
    targetPort: 3890
    protocol: TCP
    name: ldap
  - port: 17170
    targetPort: 17170
    protocol: TCP
    name: http
  selector:
    app: lldap
