---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authelia-forwardauth
  namespace: bazarr
spec:
  forwardAuth:
    address: http://authelia.authelia.svc.cluster.local:9091/api/verify?rd=https://auth.lab.jackhumes.com/
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
      - Remote-Name
      - Remote-Email
    authResponseHeadersRegex: ^Remote-
    trustForwardHeader: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: bazarr
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bazarr
  namespace: bazarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bazarr.lab.jackhumes.com`)
      kind: Rule
      middlewares:
        - name: authelia-forwardauth
      services:
        - name: bazarr
          port: 6767
  tls:
    secretName: bazarr-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bazarr-http
  namespace: bazarr
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`bazarr.lab.jackhumes.com`)
      kind: Rule
      middlewares:
        - name: redirect-https
      services:
        - name: bazarr
          port: 6767
