---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nas-cert
  namespace: nas
spec:
  secretName: nas-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - nas.lab.jackhumes.com
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nas
  namespace: nas
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nas.lab.jackhumes.com`)
      kind: Rule
      services:
        - name: nas
          port: 9999
          scheme: https
          serversTransport: nas-nas-transport@kubernetescrd
  tls:
    secretName: nas-tls
