---
apiVersion: v1
kind: Service
metadata:
  name: qui
  namespace: qui
  labels:
    app: qui
spec:
  type: ClusterIP
  ports:
    - port: 7476
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: qui
