---
apiVersion: v1
kind: Service
metadata:
  name: goflow2
  namespace: goflow2
  labels:
    app: goflow2
spec:
  selector:
    app: goflow2
  ports:
    - name: netflow
      port: 2055
      targetPort: 2055
      protocol: UDP
    - name: sflow
      port: 6343
      targetPort: 6343
      protocol: UDP
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: goflow2-netflow
  namespace: goflow2
  labels:
    app: goflow2
spec:
  type: LoadBalancer
  selector:
    app: goflow2
  ports:
    - name: netflow
      port: 2055
      targetPort: 2055
      protocol: UDP
    - name: sflow
      port: 6343
      targetPort: 6343
      protocol: UDP
