apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole-cert
  namespace: pihole
spec:
  secretName: pihole-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - pihole.lab.jackhumes.com
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole
  namespace: pihole
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pihole.lab.jackhumes.com`)
      kind: Rule
      middlewares:
        - name: tinyauth-forwardauth
      services:
        - name: pihole-web
          port: 80
  tls:
    secretName: pihole-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole-http
  namespace: pihole
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`pihole.lab.jackhumes.com`)
      kind: Rule
      services:
        - name: pihole-web
          port: 80
      middlewares:
        - name: redirect-https
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: pihole
spec:
  redirectScheme:
    scheme: https
    permanent: true
