---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: glance
  namespace: glance
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`glance.lab.jackhumes.com`)
      kind: Rule
      services:
        - name: glance
          port: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: glance-tls
  namespace: glance
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`glance.lab.jackhumes.com`)
      kind: Rule
      services:
        - name: glance
          port: 8080
  tls:
    certResolver: letsencrypt-production
