---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: glance

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - sealedsecret.yaml

configMapGenerator:
  - name: glance-config
    files:
      - glance.yml=config.yaml
