---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ntopng
  namespace: ntopng
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ntopng.lab.jackhumes.com`)
      kind: Rule
      services:
        - name: ntopng
          port: 3000
      middlewares:
        - name: authelia
          namespace: authelia
  tls:
    certResolver: letsencrypt-production
