---
apiVersion: v1
kind: Service
metadata:
  name: ntopng
  namespace: ntopng
  labels:
    app: ntopng
spec:
  # Using ClusterIP since we have hostNetwork
  # Traffic will be routed via Traefik IngressRoute
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ntopng
