---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-alerting-secrets
  namespace: grafana
spec:
  encryptedData:
    discord_webhook_url: AgA6Sqr5oHY3Ij9frFt96ReWjxf5nZZhpR1FWaA3ArE+kT9IO5a6Krl0t81LPU2OVRnOHX8jUmlDd1nzSCcARfD4oVyLCFJIwiavMHCKRqlmkAGn6MViVP1g1+lDNO0EqAlgOF+s4bMxzVaV1+buaS1TKNEVhNeI+duMa2mEsD/TkfbL8apwUKBO1PM2DtZmFn0yJmbv5n9Ag2nH+FbzINOs9MhjdlFH/zbuySm4l7dMIgUmt1CET6T2FXeLoSTY2F7S68vOea60EDMYlrqJPTtwRZSggSaCFWxYpoq6ni8RQyIfqfH9qyIznfCMvorgTdPjjzYGU3l6GjGxj/OHlLeZSRF5CxCvc9WLFZDkHMqlKo+skNRbTT8agfjIEDlNfLm4Y26hUTSo1q93VM/h7S4r6sOCk++83xEr+/n/AebWP050lKT2l2cm4MXENAPsTbnObVzezSswp6IxwfnXePWDH7Iivh1S63n61Y14l+uAo1uLaCjML/yz5Ev71isu8bkK0JASWtVDR8bOC6XUu+qzS4UBQT4BvpIbsbG7x5Ym1CRKQAIq7FhCr9YW2qfdGO5J277m7g3ZkGV4hzuzq/sZz0h3vgIVIZAjemJlWHzQEkujUP1yggkEDJ0tWwSqTmo+rhpcafgh0gpaP3bSFgp89BR4SMsz/nzE/IhlP3eclMZNFpadz+EK+NE0SRguRk93JPPmk0jZnuKbuy7zvqrAtWabewKpTwN5Aq6mDrLvOj3kxRWjJCifZTPXgZFi6eVz20eOYcUQ6XwrBzv/3D+eo038d3akazyunkrBUaEYctu+vE0jMVuR1Npl9kUQlbacs0TiE95mEaY52cSOeuEZttrSUqevDGVP
  template:
    metadata:
      name: grafana-alerting-secrets
      namespace: grafana
    type: Opaque
