---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sealedsecret.yaml
  - alerting-secret.yaml
  - configmap.yaml
  - datasources.yaml
  - dashboards-provisioning.yaml
  - dashboard-k8s-cluster.yaml
  - dashboard-pods.yaml
  - dashboard-logs.yaml
  - dashboard-k8s-global.yaml
  - dashboard-k8s-namespaces.yaml
  - dashboard-k8s-pods.yaml
  - dashboard-k8s-nodes.yaml
  - alerting.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - ingressroute.yaml
