---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc-secret
  namespace: grafana
spec:
  encryptedData:
    # Pocket ID OIDC client secret for Grafana
    client_secret: AgAj2zZxTxK6Xn+eivf3+47OkLgR9rnwIPcIYNKJOaIbLakhowxan0ywr1OmdcR3la+xptto4bs8r95jX3sIGwgJrBtyxGdIxPr/h1omcD5lkommFCMbtMTSKC3fQf1X5JSacAgTF6QnmjOxU7wW2ETFSxhoqXVoI7++BELzbbE131cIaeLDSYriroXr6QBVGje16fl1AvE8y157O8axdsR8DGXP1vCloyiuUe6SxOC+EUpzca/4cYkxTjvlBWSHlpeXA1JyFGCHXRr44wPzeeIK1XbPjyOICDI0ccuPL72aZg6ROopkWftawgtJEj1HYc1AHqvg1vSoffiKrM9JoG94ZP6gKdwDNsjKkdtXHHVYzvRrw9k5cGFqVmFsyn7YSzV2H7K5YhaZw+ZKA5nhkwtLWyEdEu0c47byDkfMg1aRjZAtw+V55bqkTMPRgmPJnqnMJZii0C7bI6NWHNNktIOUDBK2Wi1WxAcSCvonr3VPEgwT5Bl8pp0Ha3kWp6MhqTVkMeyWXC+iJ7Pc9kPnhxKB2M0ZANMKltfP8NkodukFSJuHMraJuLceNPNQH7ksUaT4+RNcBL5zLJuV3wtEbWIEDInR6IGoNnHgUPOxPkkx1VsqUjvEFIWqbIfGklgg7CXZNq/++4NSxVNLV9fTkwum/43bGDidXA4jBw5R4QFw7g7uL3DVipxgyFyK+gWWoqNnc7Uu0Je/AVxb+fWDT35iwf9S7w/EtoiX2I+WILG2Ug==
  template:
    metadata:
      name: grafana-oidc-secret
      namespace: grafana
    type: Opaque
