---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc-secret
  namespace: grafana
spec:
  encryptedData:
    # Pocket ID OIDC client secret for Grafana
    client_secret: AgAx18u2H2orQHYRUev0b2j/AhVsCc4DkeafB+8zzPc65SRyQFDsJi8vOo220MPgMeOsCroLNXYfTfu36BhZ6tIWGG0bhtaQLWf6Id0nUX8fZ6n60Ceaf7YrXCwANN3dYZvO1o+F/5m/RWef4IkL6lmxEy+NL4kvmtpRRfFAu6bmbHuRSOJugVfKQzNMub2fBwXnVK468njXvyT2ES5WQUZ20Lz7Y7yIiIz5B2TFH4tomAUalZMUvHZTCQB9NWmF4bshZpXa01f9vIkM4uKLcdVoEJmaUVsHk8wH+jYVFQcqhIoM8/LcakusKFrHjdxis0boxVTVb65oRi01+5xMbDxkqGxfCKDJzBuMNLzNKrpOG9UJNcBcX91Yh+AhO7vcC2gQ2T5b0jaGfRlBARgFz89lNrP0tB3GYZDpX46RwFmzt5lRwIc+MkgYav2YOyjoAmCo9xL7RoaoU0Oikg5AP3zt046WfS7LKzVTN4Tel0AxeJwSeoQ8NwBI3cgYeWVmJKSeYpQXiYb8ZsiQjgdGq/BnnmkYIUSGSQpnTU4eI8fMhu1x+2JiZqVsWVs44WTxKe3WA0m5AvQ8CAS9pBM8LARHfjz//7I/81XJ1cuI5RHG4q4a8+9DSQdxUUrCNg7vv+7sleR8kyUlafu8YeeWTEkDsPYqnvqAcqDV3aftc2i/084K3p36wwJDglx8K71jU5dB1RYdzTYIY61RWUqMjA99YPNHXJaCvZPFnWOxQFAfu4c/ORHwt1+Uriaogw==
  template:
    metadata:
      name: grafana-oidc-secret
      namespace: grafana
    type: Opaque
