---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: prometheus
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prometheus.lab.jackhumes.com`)
      kind: Rule
      middlewares:
        - name: tinyauth-forwardauth
      services:
        - name: prometheus
          port: 9090
  tls:
    secretName: prometheus-tls
