---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: authelia-forwardauth
  namespace: prometheus
spec:
  forwardAuth:
    address: http://authelia.authelia.svc.cluster.local:9091/api/verify?rd=https://auth.lab.jackhumes.com/
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
      - Remote-Name
      - Remote-Email
    authResponseHeadersRegex: ^Remote-
    trustForwardHeader: true
