---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: netbird

resources:
  - namespace.yaml
  - configmap.yaml
  - sealedsecret.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
