---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unpoller-config
  namespace: unpoller
data:
  unpoller.conf: |
    [poller]
      debug = false
      quiet = false
      
    [prometheus]
      disable = false
      http_listen = "0.0.0.0:9130"
      report_errors = false
      
    [influxdb]
      disable = true
      
    [unifi]
      dynamic = false
      
    [[unifi.controller]]
      url = "https://192.168.1.1"
      user = "unpoller"
      pass = "env:UNIFI_PASSWORD"
      verify_ssl = false
      save_sites = true
      save_ids = false
      save_events = false
      save_alarms = false
      save_anomalies = false
      save_dpi = true
